# Generated by Django 5.2.6 on 2026-08-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishyashravyakosha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='drishyashravyakoshaentry',
            name='presenters',
            field=models.ManyToManyField(blank=True, related_name='entries', to='drishyashravyakosha.presenter'),
        ),
    ]
