# Generated by Django 5.2.6 on 2026-09-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kavi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrasangaYadiEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_number', models.CharField(blank=True, max_length=50, null=True)),
                ('prasanga_name', models.CharField(max_length=500)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_status', models.CharField(blank=True, max_length=100, null=True)),
                ('prasanga_type', models.CharField(blank=True, max_length=100, null=True)),
                ('prasanga_language', models.CharField(blank=True, max_length=100, null=True)),
                ('story_source', models.CharField(blank=True, max_length=255, null=True)),
                ('prasanga_kosha_link', models.URLField(blank=True, max_length=500, null=True)),
                ('pratisangraha_link', models.URLField(blank=True, max_length=500, null=True)),
                ('kavi', models.ManyToManyField(blank=True, related_name='entries', to='prasangayadi.kavi')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
