# Generated by Django 5.2.6 on 2026-07-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustakakosha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pustakakoshaentry',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pustakakoshaentry',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
