# Generated by Django 5.2.6 on 2026-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustakakosha', '0002_pustakakoshaentry_more_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pustakakoshaentry',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
