# Generated by Django 5.2.6 on 2026-07-27 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanghatanaKoshaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_of_the_org', models.CharField(max_length=500)),
                ('details', models.TextField(blank=True, null=True)),
                ('type_of_org', models.CharField(blank=True, max_length=255, null=True)),
                ('yakshagana_category', models.CharField(blank=True, max_length=255, null=True)),
                ('yakshagana_sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('estabishment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('state_of_the_est', models.CharField(blank=True, max_length=255, null=True)),
                ('head_quarter', models.CharField(blank=True, max_length=500, null=True)),
                ('details_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
