# Generated by Django 5.2.6 on 2026-07-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filterconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, unique=True)),
                ('fields', models.JSONField(default=list)),
            ],
        ),
    ]
