# Generated by Django 5.2.6 on 2026-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitehomeconfig_siteupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitehomeconfig',
            name='maintenance_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitehomeconfig',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
