# Generated by Django 5.2.6 on 2026-07-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattukosha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mattukoshaentry',
            old_name='name_of_the_mattu',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mattukoshaentry',
            old_name='link_to_pdf_document',
            new_name='pdf_link',
        ),
        migrations.AddField(
            model_name='mattukoshaentry',
            name='ragas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mattukoshaentry',
            name='situations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mattukoshaentry',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
