# Generated by Django 5.2.6 on 2026-08-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattukosha', '0003_ragas_situations_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattukoshaentry',
            name='unique_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
